### ISSUE TITLE
pretty sure u dont know what a rootkit is lol

### ISSUE THREAD

**Issue by StvnedEagle1337** [spooldev/SpoolWare#2]
lol

**Comment by spooldev** [comment]
Hello there,

Google definition: "a set of software tools that enable an unauthorized user to gain control of a computer system without being detected" 

Spoolware is designed to give someone control of a system, while also acting as a bus for more software's.

Kind regards,
Spool

**Comment by StvnedEagle1337** [comment]
My bad i read something wrong in the repos readme!
